import re
from html import escape


def markdown_to_telegram_html(text: str) -> str:
    """Convert common Markdown generated by LLMs into Telegram-safe HTML."""
    if not text:
        return text

    safe = escape(text, quote=False)

    # Strong emphasis
    safe = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", safe)
    safe = re.sub(r"__([\w\s\-]+?)__", r"<b>\1</b>", safe)

    # Emphasis
    safe = re.sub(r"(?<!\*)\*(?!\*)([^*]+?)(?<!\*)\*(?!\*)", r"<i>\1</i>", safe)
    safe = re.sub(r"(?<!_)_(?!_)([^_]+?)(?<!_)_(?!_)", r"<i>\1</i>", safe)

    # Inline code
    safe = re.sub(r"`([^`]+)`", r"<code>\1</code>", safe)

    # Strikethrough
    safe = re.sub(r"~~(.+?)~~", r"<s>\1</s>", safe)

    # Links
    safe = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)", r'<a href="\2">\1</a>', safe)

    # Headers: convert Markdown # headings to bold lines
    safe = re.sub(r"(?m)^#{1,6}\s*(.*)$", r"<b>\1</b>", safe)

    # Blockquotes
    safe = re.sub(r"(?m)^>\s*(.*)$", r"<blockquote>\1</blockquote>", safe)

    # Lists
    safe = re.sub(r"(?m)^\s*[-*]\s+(.*)$", r"• \1", safe)
    safe = re.sub(r"(?m)^\s*\d+\.\s+(.*)$", r"• \1", safe)

    # Code blocks (fenced)
    safe = re.sub(r"```(?:\w+)?\n?(.*?)```", lambda m: "<pre>" + escape(m.group(1), quote=False) + "</pre>", safe, flags=re.DOTALL)

    # Preserve paragraphs/newlines, but make them Telegram-friendly
    safe = safe.replace("\r\n", "\n")
    return safe
